version: '3.3'

networks:
  lourd:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart : always
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - lourd
    volumes:
      - postgres-data:/var/lib/postgresql/data


  backend:
    build:
      context: ./back
      target: back-build
    env_file:
      - .env
    ports:
      - '3001:3001'
      - '5555:5555'
    networks:
      - lourd
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules

#  frontend:
#    build:
#      context: ./front
#      target: front-build
#    env_file:
#      - .env
#    ports:
#      - '3000:3000'
#    networks:
#      - lourd
#    depends_on:
#      - backend
#    restart: unless-stopped
#    volumes:
#      - ./front:/usr/src/app
#      - /usr/src/app/node_modules

  nestjs-shell:
    image: node:18-alpine
    entrypoint: /bin/sh


volumes:
  postgres-data:

