version: '3.3'

networks:
  lourd:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart : always
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - lourd
    volumes:
      - postgres-data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      target: Rex
    env_file:
      - .env
    ports:
      - '3001:3001'
      - '5555:5555'
    networks:
      - lourd
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres-data:

