version: '3'
services:
  Backend:
    image: nestjs/cli:latest
    env_file:
      - .env # environment variables
    environment:
      JWT_SECRET: $JWT_SECRET
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env # environment variables
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '5432:5432'
