version: '3.3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: . 
    env_file:
      - .env # environment variables
    environment:
      JWT_SECRET: $JWT_SECRET
    ports:
      - '3000:3000'
      - '5555:5556'
    depends_on:
      - db
    networks:
      - lourd
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - .env # environment variables
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    networks:
      - lourd

networks:
  lourd:
    driver: bridge